edition = "2018"
unstable_features = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
max_width = 120
newline_style = "Unix"
use_field_init_shorthand = true
