DROP TABLE IF EXISTS pre_users;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS curr_rooms;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS records;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS rules;
