//! Main file of binary file
//!
//! Main function is used to call the internal main function.

/// Main function
///
/// Actual main function is generated by `actix_web::main`
#[cfg(not(tarpaulin_include))]
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    server::internal::main().await
}
